FROM python:3.9-slim

RUN pip install mlflow

CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5002", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "/mlflow/artifacts"]
