FROM python:3.10-slim
# Set the working directory to /app
RUN pip install --upgrade pip && \
    pip install pyarrow pymilvus 
   
RUN pip install --upgrade pip && \
    pip install pyarrow pymilvus \
	&& pip install \
    pandas \
    transformers \
    torch \
    fastapi \
    flask \ 
    zenml \
    requests \
    psycopg2-binary
    # \
    # uvicorn[standard] \
    # zenml[server]>=0.50.0 \
    # notebook \
    # scikit-learn
 
RUN    pip install --upgrade pymilvus==v2.3.7

WORKDIR /app

# Copy the current directory contents into the container at /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install cryptography
# Install any needed packages specified in requirements.txt
# requirements.txt
COPY . /app
# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World

# Run app.py when the container launches
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8081", "--reload"]
# # # Use a stable version of Python.
# # FROM python:3.10-slim
# FROM python:3.10-slim

# # Set the working directory in the container
# RUN mkdir -p /opt/webapi/app
# WORKDIR /opt/webapi/app

# # Copy the dependencies file to the working directory
# COPY requirements.txt .

# # Install any dependencies
# RUN pip install --no-cache-dir -r requirements.txt
# RUN pip install uvicorn
# RUN pip install uvicorn


# # Display Python and Pip paths
# RUN which python
# RUN which pip

# # List installed packages
# RUN pip list

# # Attempt to find the uvicorn executable explicitly
# RUN find / -name uvicorn

# COPY . /opt/webapi/app/

# COPY requirements.txt /opt/webapi/app

# EXPOSE 80

# # Specify the command to run on container start
# CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]

# # # Set the working directory in the container
# # WORKDIR /opt/app

# # # Copy the dependencies file to the working directory



# # # Install any dependencies
# # RUN pip install --no-cache-dir -r requirements.txt

# # # COPY requirements.txt .
# # # RUN pip install --no-cache-dir -r requirements.txt
# # RUN pip install uvicorn


# # # Copy the content of the local src directory to the working directory
# # COPY . .

# # # Command to run on container start
# # CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]


# # # FROM python:3.10-slim
# # # RUN mkdir -p /opt/app
# # # WORKDIR /opt/app
# # # COPY requirements.txt requirements.txt
# # # RUN pip install -r requirements.txt
# # # COPY . .
# # # # RUN pip install -r requirements.txt
# # # COPY . .
# # # CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
