  pipelines:
    pipeline1:
      steps:
        - name: load_data
          source: load_data
          parameters:
            path: "/home/shiku/repo/dang.milvus_zenml_docker/data/input/qustions_answers/mental_health_faq.csv"
        - name: train_model
          source: train_model
          depends_on:
            - load_data
    pipeline2:
      steps:
        - name: step_one
          source: step_one
          parameters:
            param1: "value1"
        - name: step_two
          source: step_two
          depends_on:
            - step_one
